[[header]]

[[content]]
[[concurrent_node_map]]
=== 类模板 concurrent++_++node++_++map

`boost::concurrent++_++node++_++map` ——
一种基于节点的哈希表，用于建立唯一键与对应值的关联，并支持在无外部同步机制的情况下并发执行元素插入、擦除、查找和访问操作。

尽管 `boost::concurrent++_++node++_++map`
的行为类似于容器，但它并不符合标准 C{plus}{plus} 的
 https://en.cppreference.com/w/cpp/named_req/Container[容器]概念模型。具体而言，它不提供迭代器及相关操作（如
`begin`、`end`
等）。元素的访问和修改通过用户提供的__访问函数__来实现，这些函数被传递至
`concurrent++_++node++_++map`
的操作中，并在其内部以受控方式执行。这种基于访问的 API
设计能够支持低争用的并发应用场景。

`boost::concurrent++_++node++_++map` 的内部数据结构与
`boost::unordered++_++node++_++map` 类似。与
`boost::concurrent++_++flat++_++map`
不同，它提供了指针稳定性和节点处理功能，但代价是可能带来性能上的损失。

[[concurrent_node_map_synopsis]]
==== 概要

....
// #include <boost/unordered/concurrent_node_map.hpp>

namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class concurrent_node_map {
  public:
    // 类型
    using key_type             = Key;
    using mapped_type          = T;
    using value_type           = std::pair<const Key, T>;
    using init_type            = std::pair<
                                   typename std::remove_const<Key>::type,
                                   typename std::remove_const<T>::type
                                 >;
    using hasher               = Hash;
    using key_equal            = Pred;
    using allocator_type       = Allocator;
    using pointer              = typename std::allocator_traits<Allocator>::pointer;
    using const_pointer        = typename std::allocator_traits<Allocator>::const_pointer;
    using reference            = value_type&;
    using const_reference      = const value_type&;
极简风格>    using size_type            = std::size_t;
    using difference_type      = std::ptrdiff_t;

    using node_type            = 实现定义;
    using insert_return_type   = 实现定义;

    using stats                = 统计类型; // 若统计功能已启用

    // 常量
    static constexpr size_type bulk_visit_size = 实现定义;

    // 构造/复制/销毁
    concurrent_node_map();
    explicit concurrent_node_map(size_type n,
                                 const hasher& hf = hasher(),
                                 const key_equal& eql = key_equal(),
                                 const allocator_type& a = allocator_type());
    template<class InputIterator>
      concurrent_node_map(InputIterator f, InputIterator l,
                          size_type n = 实现定义,
                          const hasher& hf = hasher(),
                          const key_equal& eql = key_equal(),
                          const allocator_type& a = allocator_type());
    concurrent_node_map(const concurrent_node_map& other);
    concurrent_node_map(concurrent_node_map&& other);
    template<class InputIterator>
      concurrent_node_map(InputIterator f, InputIterator l,const allocator_type& a);
    explicit concurrent_node_map(const Allocator& a);
    concurrent_node_map(const concurrent_node_map& other, const Allocator& a);
    concurrent_node_map(concurrent_node_map&& other, const Allocator& a);
    concurrent_node_map(unordered_node_map<Key, T, Hash, Pred, Allocator>&& other);
    concurrent_node_map(std::initializer_list<value_type> il,
                        size_type n = 实现定义
                        const hasher& hf = hasher(),
                        const key_equal& eql = key_equal(),
                        const allocator_type& a = allocator_type());
    concurrent_node_map(size_type n, const allocator_type& a);
    concurrent_node_map(size_type n, const hasher& hf, const allocator_type& a);
    template<class InputIterator>
      concurrent_node_map(InputIterator f, InputIterator l, size_type n,
                          const allocator_type& a);
    template<class InputIterator>
      concurrent_node_map(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
    concurrent_node_map(std::initializer_list<value_type> il, const allocator_type& a);
    concurrent_node_map(std::initializer_list<value_type> il, size_type n,
                        const allocator_type& a);
    concurrent_node_map(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                        const allocator_type& a);
    ~concurrent_node_map();
    concurrent_node_map& operator=(const concurrent_node_map& other);
    concurrent_node_map& operator=(concurrent_node_map&& other) noexcept(
      (boost::allocator_traits<Allocator>::is_always_equal::value ||
       boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
       std::is_same<pointer, value_type*>::value);
    concurrent_node_map& operator=(std::initializer_list<value_type>);
    allocator_type get_allocator() const noexcept;


    // 访问
    template<class F> size_t visit(const key_type& k, F f);
    template<class F> size_t visit(const key_type& k, F f) const;
    template<class F> size_t cvisit(const key_type& k, F f) const;
    template<class K, class F> size_t visit(const K& k, F f);
    template<class K, class F> size_t visit(const K& k, F f) const;
    template<class K, class F> size_t cvisit(const K& k, F f) const;

    template<class FwdIterator, class F>
      size_t visit(FwdIterator first, FwdIterator last, F f);
    template<class FwdIterator, class F>
      size>t visit(FwdIterator first, FwdIterator last, F f) const;
    template<class FwdIterator, class F>
      size_t cvisit(FwdIterator first, FwdIterator last, F f) const;

    template<class F> size_t visit_all(F f);
    template<class F> size_t visit_all(F f) const;
    template<class F> size_t cvisit_all(F f) const;
    template<class ExecutionPolicy, class F>
      void visit_all(ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      void visit_all(ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      void cvisit_all(ExecutionPolicy&& policy, F f) const;

    template<class F> bool visit_while(F f);
    template<class F> bool visit_while(F f) const;
    template<class F> bool cvisit_while(F f) const;
    template<class ExecutionPolicy, class F>
      bool visit_while(ExecutionPolicy&& policy, F f);
    template<class ExecutionPolicy, class F>
      bool visit_while(ExecutionPolicy&& policy, F f) const;
    template<class ExecutionPolicy, class F>
      bool cvisit_while(ExecutionPolicy&& policy, F f) const;

    // 容量
    [[nodiscard]] bool empty() const noexcept;
    size_type size() const noexcept;
    size_type max_size() const noexcept;

    // 修改器
    template<class... Args> bool emplace(Args&&... args);
    bool insert(const value_type& obj);
    bool insert(const init_type& obj);
    bool insert(value_type&& obj);
    bool insert(init_type&& obj);
    template<class InputIterator> size_type insert(InputIterator first, InputIterator last);
    size_type insert(std::initializer_list<value_type> il);
    insert_return_type insert(node_type&& nh);

    template<class... Args, class F> bool emplace_or_visit(Args&&... args, F&& f);
    template<class... Args, class F> bool emplace_or_cvisit(Args&&... args, F&& f);
    template<class F> bool insert_or_visit(const value_type& obj, F f);
    template<class F> bool insert_or_cvisit(const value_type& obj, F f);
    template<class F> bool insert_or_visit(const init_type& obj, F f);
    template<class F> bool insert_or_cvisit(const init_type& obj, F f);
    template<class F> bool insert_or_visit(value_type&& obj, F f);
    template<class F> bool insert_or_cvisit(value_type&& obj, F f);
    template<class F> bool insert_or_visit(init_type&& obj, F f);
    template<class F> bool insert_or_cvisit(init_type&& obj, F f);
    template<class InputIterator,class F>
      size_type insert_or_visit(InputIterator first, InputIterator last, F f);
    template<class InputIterator,class F>
      size_type insert_or_cvisit(InputIterator first, InputIterator last, F f);
    template<class F> size_type insert_or_visit(std::initializer_list<value_type> il, F f);
    template<class F> size_type insert_or_cvisit(std::initializer_list<value_type> il, F f);
    template<class F> insert_return_type insert_or_visit(node_type&& nh, F f);
    template<class F> insert_return_type insert_or_cvisit(node_type&& nh, F f);

    template<class... Args, class F1, class F2>
      bool emplace_and_visit(Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool emplace_and_cvisit(Args&&... args, F1&& f1, F2&& f2);
    template<class F1, class F2> bool insert_and_visit(const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_cvisit(const value_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_visit(const init_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_cvisit(const init_type& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_visit(value_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_cvisit(value_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_visit(init_type&& obj, F1 f1, F2 f2);
    template<class F1, class F2> bool insert_and_cvisit(init_type&& obj, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type insert_and_visit(InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class InputIterator,class F1, class F2>
      size_type insert_and_cvisit(InputIterator first, InputIterator last, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type insert_and_visit(std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      size_type insert_and_cvisit(std::initializer_list<value_type> il, F1 f1, F2 f2);
    template<class F1, class F2>
      insert_return_type insert_and_visit(node_type&& nh, F1 f1, F2 f2);
    template<class F1, class F2>
      insert_return_type insert_and_cvisit(node_type&& nh, F1 f1, F2 f2);

    template<class... Args> bool try_emplace(const key_type& k, Args&&... args);
    template<class... Args> bool try_emplace(key_type&& k, Args&&... args);
    template<class K, class... Args> bool try_emplace_or_visit(const key_type& k, Args&&... args, F&& f);
    template<class... Args, class F>
      bool try_emplace_or_cvisit(const key_type& k, Args&&... args, F&& f);
    template<class... Args, class F>
      bool try_emplace_or_visit(key_type&& k, Args&&... args, F&& f);
    template<class... Args, class F>
      bool try_emplace_or_cvisit(key_type&& k, Args&&... args, F&& f);
    template<class K, class... Args, class F>
      bool try_emplace_or_visit(K&& k, Args&&... args, F&& f);
    template<class K, class... Args, class F>
      bool try_emplace_or_cvisit(K&& k, Args&&... args, F&& f);

    template<class... Args, class F1, class F2>
      bool try_emplace_and_visit(const key_type& k, Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool try_emplace_and_cvisit(const key_type& k, Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool try_emplace_and_visit(key_type&& k, Args&&... args, F1&& f1, F2&& f2);
    template<class... Args, class F1, class F2>
      bool try_emplace_and_cvisit(key_type&& k, Args&&... args, F1&& f1, F2&& f2);
    template<class K, class... Args, class F1, class F2>
      bool try_emplace_and_visit(K&& k, Args&&... args, F1&& f1, F2&& f2);
    template<class K, class... Args, class F1, class F2>
      bool try_emplace_and_cvisit(K&& k, Args&&... args, F1&& f1, F2&& f2);


    template<class M> bool insert_or_assign(const key_type& k, M&& obj);
    template<class M> bool insert_or_assign(key_type&& k, M&& obj);
    template<class K, class M> bool insert_or_assign(K&& k, M&& obj);

    size_type erase(const key_type& k);
    template<class K> size_type erase(const K& k);

    template<class F> size_type erase_if(const key_type& k, F f);
    template<class K, class F> size_type erase_if(const K& k, F f);
    template<class F> size_type erase_if(F f);
    template<class ExecutionPolicy, class  F> void erase_if(ExecutionPolicy&& policy, F f);

    void      swap(concurrent_node_map& other)
      noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
               boost::allocator_traits<Allocator>::propagate_on_container_swap::value);

    node_type extract(const key_type& k);
    template<class K> node_type extract(const K& k);

    template<class F> node_type extract_if(const key_type& k, F f);
    template<class K, class F> node_type extract_if(const K& k, F f);

    void      clear() noexcept;

    template<class H2, class P2>
      size_type merge(concurrent_node_map<Key, T, H2, P2, Allocator>& source);
    template<class H2, class P2>
      size_type merge(concurrent_node_map<Key, T, H2, P2, Allocator>&& source);

    // 观察器
    hasher hash_function() const;
    key_equal key_eq() const;

    // 映射操作
    size_type        count(const key_type& k) const;
    template<class K>
      size_type      count(const K& k) const;
    bool             contains(const key_type& k) const;
    template<class K>
      bool           contains(const K& k) const;

    // 桶接口
    size_type bucket_count() const noexcept;

    // 哈希策略
    float load_factor() const noexcept;
    float max_load_factor() const noexcept;
    void max_load_factor(float z);
    size_type max_load() const noexcept;
    void rehash(size_type n);
    void reserve(size_type n);

    // 统计（若启用）
    stats get_stats() const;
    void reset_stats() noexcept;
  };

  // 推导指引
  template<class InputIterator,
           class Hash = boost::hash<迭代器键类型<InputIterator>>,
           class Pred = std::equal_to<迭代器键类型<InputIterator>>,
           class Allocator = std::allocator<迭代器到分配类型<InputIterator>>>
    concurrent_node_map(InputIterator, InputIterator, typename 见下文::size_type = 见下文,
                        Hash = Hash(), Pred = Pred(), Allocator = Allocator())
      -> concurrent_node_map<迭代器键类型<InputIterator>, 迭代器映射类型<InputIterator>, Hash,
                             Pred, Allocator>;

  template<class Key, class T, class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
    concurrent_node_map(std::initializer_list<std::pair<Key, T>>,
                        typename 见下文::size_type = 见下文::size_type, Allocator)
      -> concurrent_node_map<迭代器键类型<InputIterator>, 迭代器映射类型a><InputIterator>,
                             boost::hash<迭代器键类型<InputIterator>>,
                             std::equal_to<迭代器键类型<InputIterator>>, Allocator>;

  template<class InputIterator, class Allocator>
    concurrent_node_map(InputIterator, InputIterator, Allocator)
      -> concurrent_node_map<迭代器键类型<InputIterator>, 迭代器映射类型<InputIterator>,
                             boost::hash<迭代器键类型<InputIterator>>,
                             std::equal_to<迭代器键类型<InputIterator>>, Allocator>;

  template<class InputIterator, class Hash, class Allocator>
    concurrent_node_map(InputIterator, InputIterator, typename 见下文::size_type, Hash,
                        Allocator)
      -> concurrent_node_map<迭代器键类型<InputIterator>, 迭代器映射类型<InputIterator>, Hash,
                             std::equal_to<迭代器键类型<InputIterator>>, Allocator>;

  template<class Key, class T, class Allocator>
    concurrent_node_map(std::initializer_list<std::pair<Key, T>>, typename 见下文::size_type,
                        Allocator)
      -> concurrent_node_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Allocator>
    concurrent_node_map(std::initializer_list<std::pair<Key, T>>, Allocator)
      -> concurrent_node_map<Key, T, boost::hash<Key>, std::equal_to<Key>, Allocator>;

  template<class Key, class T, class Hash, class Allocator>
    concurrent_node_map(std::initializer_list<std::pair<Key, T>>, typename 见下文::size_type,
                        Hash, Allocator)
      -> concurrent_node_map<Key, T, Hash, std::equal_to<Key>, Allocator>;

} // namespace unordered
} // namespace boost
....

'''''

[[concurrent_node_map_description]]
==== 描述

*模板参数*

[width="100%",cols="50%,50%",]
|===
|_键_ |`std::pair++<++const Key, T++>++` 必须能够从任何可转换为该类型的
`std::pair`
对象https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible[原地构造]到容器中，并且必须支持从容器中 https://en.cppreference.com/w/cpp/named_req/Erasable[擦除]。

|_T_ |

|_Hash_ |一元函数对象类型，用作 `Key` 的哈希函数。它接受一个类型为 `Key`
的参数，并返回一个 `std::size++_++t` 类型的值。

|_谓词_ |二元函数对象，用于在 `Key`
类型的值上建立等价关系。它接受两个类型为 `Key` 的参数，并返回一个 `bool`
类型的值。

|_分配器_
|一种分配器，其值类型与容器的值类型相同。支持使用link:https://en.cppreference.com/w/cpp/named_re极/Allocator#Fancy_pointers[花式指针]的分配器。
|===

容器的元素节点存储在内部的__桶数组__中。节点根据其元素的哈希码被插入到对应的桶中，但如果该桶已被占用（即发生__冲突__），则会使用原始位置附近可用的桶。

桶数组的大小可通过调用 `insert`/`emplace` 自动增加，也可通过调用
`rehash`/`reserve`
进行调整。容器的__负载因子__（元素数量与桶数量的比值）永远不会超过
`max++_++load++_++factor()`，但在小规模数据情况下，实现可能允许更高的负载因子。

若
link:../../../../../container_hash/doc/html/hash.html#ref_hash_is_avalanchinghash[`hash++_++is++_++avalanching`]`++<++Hash++>++::value`
为
`true`，则直接使用哈希函数；否则，会添加一个位混合后处理阶段以提高哈希质量，但会牺牲额外的计算成本。

'''''

[[concurrent_node_map_concurrency_requirements_and_guarantees]]
==== 并发要求与保证

要求对同一 `Hash` 或 `Pred` 常量实例并发调用 `operator()`
时不得引入数据竞争。对于 `Alloc`（即 `Allocator`
或其重绑定后的任意分配器类型），在同一实例 `al`
上并发调用以下操作时不得引入数据竞争：

* 从 `al` 复制构造重新绑定的分配器
* `std::allocator++_++traits++<++Alloc++>++::allocate`
* `std::allocator++_++traits++<++Alloc++>++::deallocate`
* `std::allocator++_++traits++<++Alloc++>++::construct`
* `std::allocator++_++traits++<++Alloc++>++::destroy`

通常而言，若 `Hash`、`Pred` 和 `Allocator`
这些类型不包含状态，或其操作仅涉及对内部数据成员的常量访问，即可满足上述要求。

除析构操作外，对同一个 `concurrent++_++node++_++map`
实例并发调用任何操作都不会引入数据竞争——即这些操作是线程安全的。

如果某个操作 *op* 被显式指定为__阻塞于__ `x`（其中 `x` 是
`boost::concurrent++_++node++_++map` 的实例），则先前对 `x`
的阻塞操作将与 *op* 同步。因此，在多线程场景中，对同一
`concurrent++_++node++_++map` 的阻塞操作将按顺序执行。

若某个操作仅在触发内部重哈希时才会阻塞于 _`x`_，则称该操作__阻塞于 _`x`_
的重哈希过程__。

当由 `boost::concurrent++_++node++_++map`
在内部执行时，用户提供的访问函数对传递的元素执行以下操作不会引入数据竞争：

* 对元素的读取访问。
* 对元素的非可变修改。
* 对元素的可变修改：
+
** 在容器接受两个访问函数的操作中，此条件始终适用于第一个访问函数。
** 在名称不包含 `cvisit`
的非常量容器函数中，此条件适用于最后一个（或唯一一个）访问函数。

任何插入或修改元素 `e` 的
`boost::concurrent++_++node++_++map 操作`都会与对 `e`
执行的内部访问函数的调用同步。

由 `boost::concurrent++_++node++_++map`实例 `x` 执行的访问函数不允许调用
`x` 上的任何操作；仅当对另一 `boost::concurrent++_++node++_++map` 实例
`y` 的并发未完成操作不会直接或间接访问 `x` 时，才会允许调用 `y`
上的操作。

'''''

[[concurrent_node_map_configuration_macros]]
==== 配置宏

[[concurrent_node_map_boost_unordered_disable_reentrancy_check]]
===== `BOOST++_++UNORDERED++_++DISABLE++_++REENTRANCY++_++CHECK`

在调试版本中（更准确地说，当未定义
link:../../../../../assert/doc/html/assert.html#boost_assert_is_void[`BOOST++_++ASSERT++_++IS++_++VOID`]
时），系统会检测__容器重入__行为（即在访问 `m` 元素的函数内部非法调用
`m` 上的操作），并通过 `BOOST++_++ASSERT++_++MSG`
发出信号。若需关注运行时速度，可通过全局定义此宏来禁用该功能。

'''''

[[concurrent_node_map_boost_unordered_enable_stats]]
===== `BOOST++_++UNORDERED++_++ENABLE++_++STATS`

全局定义此宏以启用容器的 link:reference/stats_zh_Hans.adoc#stats[统计计算]
功能。请注意，此选项会降低多数操作的总体性能。

'''''

[[concurrent_node_map_typedefs]]
==== 类型定义

[source,highlight]
----
typedef  实现定义  node_type;
----

用于保存提取的表元素的类，建模为
 https://en.cppreference.com/w/cpp/container/node_handle[NodeHandle]。

'''''

[source,highlight]
----
typedef  实现定义  insert_return_type;
----

内部类模板的特化：

[source,highlight]
----
template<class NodeType>
struct insert_return_type // 名称仅用于说明
{
  bool     inserted;
  NodeType node;
};
----

其中 `NodeType` = `node++_++type`。

'''''

[[concurrent_node_map_constants]]
==== 常量

[source,highlight]
----
static constexpr size_type bulk_visit_size;
----

在link:#concurrent_node_map_bulk_visit[批量访问]操作中内部使用的数据块大小。

'''''

[[concurrent_node_map_constructors]]
==== 构造函数

[[concurrent_node_map_default_constructor]]
===== 默认构造函数

[source,highlight]
----
concurrent_node_map();
----

构造一个空容器，使用 `hasher()` 作为哈希函数，`key++_++equal()`
作为键相等性谓词，`allocator++_++type()` 作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |若使用默认值，则 `hasher`、`key++_++equal` 和
`allocator++_++type` 需满足
 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_bucket_count_constructor]]
===== 桶数构造函数

[source,highlight]
----
explicit concurrent_node_map(size_type n,
                             const hasher& hf = hasher(),
                             const key_equal& eql = key_equal(),
                             const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`eql`
作为键相等性谓词、`a` 作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |若使用默认值，则 `hasher`、`key++_++equal` 和
`allocator++_++type` 需满足
 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_iterator_range_constructor]]
===== 迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  concurrent_node_map(InputIterator f, InputIterator l,
                      size_type n = 实现定义,
                      const hasher& hf = hasher(),
                      const key_equal& eql = key_equal(),
                      const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`eql`
作为键相等性谓词、`a` 作为分配器，并将 `++[++f, l)`
范围内的元素插入其中。

[cols=",",]
|===
|要求： |若使用默认值，则 `hasher`、`key++_++equal` 和
`allocator++_++type` 需满足
 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_copy_constructor]]
===== 复制构造函数

[source,highlight]
----
concurrent_node_map(concurrent_node_map const& other);
----

复制构造函数。复制其所包含的元素、哈希函数、谓词及分配器。

若 `Allocator::select++_++on++_++container++_++copy++_++construction`
存在且签名正确，则将根据其结果来构造分配器。

[cols=",",]
|===
|要求： |`value++_++type` 必须满足可复制构造要求
|并发性： |阻塞于 `other`。
|===

'''''

[[concurrent_node_map_move_constructor]]
===== 移动构造函数

[source,highlight]
----
concurrent_node_map(concurrent_node_map&& other);
----

移动构造函数。`other`
的内部桶数组直接转移至新容器。哈希函数、谓词和分配器从 `other`
移动构造。若统计功能link:#concurrent_node_map_boost_unordered_enable_stats[已启用]，则同步转移
`other` 的内部统计信息并调用 `other.reset++_++stats()`。

[cols=",",]
|===
|并发性： |阻塞于 `other`。
|===

'''''

[[concurrent_node_map_iterator_range_constructor_with_allocator]]
===== 带分配器的迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  concurrent_node_map(InputIterator f, InputIterator l, const allocator_type& a);
----

构造一个空容器，使用 `a`
作为分配器以及默认的哈希函数和键相等性谓词，并将 `++[++f, l)`
范围内的元素插入其中。

[cols=",",]
|===
|要求： |`hasher`、`key++_++equal`
需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_allocator_constructor]]
===== 分配器构造函数

[source,highlight]
----
explicit concurrent_node_map(Allocator const& a);
----

使用分配器 `a` 构造一个空容器。

'''''

[[concurrent_node_map_copy_constructor_with_allocator]]
===== 带分配器的复制构造函数

[source,highlight]
----
concurrent_node_map(concurrent_node_map const& other, Allocator const& a);
----

构造一个容器，复制 `other` 中的元素、哈希函数及谓词，但使用分配器 `a`。

[cols=",",]
|===
|并发性： |阻塞于 `other`。
|===

'''''

[[concurrent_node_map_move_constructor_with_allocator]]
===== 带分配器的移动构造函数

[source,highlight]
----
concurrent_node_map(concurrent_node_map&& other, Allocator const& a);
----

若 `a == other.get++_++allocator()`，则 `other`
的元素直接转移至新容器；否则，元素从 `other` 移动构造。哈希函数和谓词从
`other` 移动构造，分配器从 `a`
复制构造。若统计功能link:#concurrent_node_map_boost_unordered_enable_stats[已启用]，则当
`a == other.get++_++allocator()` 时同步转移 `other`
的内部统计信息，并始终调用 `other.reset++_++stats()`。

[cols=",",]
|===
|并发性： |阻塞于 `other`。
|===

'''''

[[concurrent_node_map_move_constructor_from_unordered_node_map]]
===== 从 unordered++_++node++_++map 的移动构造函数

[source,highlight]
----
concurrent_node_map(unordered_node_map<Key, T, Hash, Pred, Allocator>&& other);
----

从 link:#unordered_node_map[`unordered++_++node++_++map`]
进行移动构造。`other`
的内部桶数组直接转移至新容器。哈希函数、谓词和分配器从 `other`
移动构造。若统计功能link:#concurrent_node_map_boost_unordered_enable_stats[已启用]，则同时转移
`other` 的内部统计信息并调用 `other.reset++_++stats()`。

[cols=",",]
|===
|复杂度： |O(`bucket++_++count()`)
|===

'''''

[[concurrent_node_map_initializer_list_constructor]]
===== 初始化列表构造函数

[source,highlight]
----
concurrent_node_map(std::initializer_list<value_type> il,
                    size_type n = 实现定义
                    const hasher& hf = hasher(),
                    const key_equal& eql = key_equal(),
                    const allocator_type& a = allocator_type());
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`eql`
作为键相等性谓词、`a` 作为分配器，并 `il` 中的元素插入其中。

[cols=",",]
|===
|要求： |若使用默认值，则 `hasher`、`key++_++equal` 和
`allocator++_++type` 需满足
 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_bucket_count_constructor_with_allocator]]
===== 带分配器的桶数构造函数

[source,highlight]
----
concurrent_node_map(size_type n, allocator_type const& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf`
作为哈希函数、默认的键相等性谓词以及 `a` 作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |`hasher` 与 `key++_++equal`
需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_bucket_count_constructor_with_hasher_and_allocator]]
===== 带哈希函数和分配器的桶数构造函数

[source,highlight]
----
concurrent_node_map(size_type n, hasher const& hf, allocator_type const& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf`
作为哈希函数、默认的键相等性谓词、以及 `a` 作为分配器。

[cols=",",]
|===
|后置条件： |`size() == 0`

|要求： |`key++_++equal`
需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_iterator_range_constructor_with_bucket_count_and_allocator]]
===== 带桶数和分配器的迭代器范围构造函数

[source,highlight]
----
template<class InputIterator>
  concurrent_node_map(InputIterator f, InputIterator l, size_type n, const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `a`
作为分配器以及默认的哈希函数和键相等性谓词，并将 `++[++f, l)`
范围内的元素插入其中。

[cols=",",]
|===
|要求： |`hasher`、`key++_++equal`
需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_iterator_range_constructor_with_bucket_count_and_hasher]]
===== 带桶数和哈希函数的迭代器范围构造函数

[source,highlight]
----
    template<class InputIterator>
      concurrent_node_map(InputIterator f, InputIterator l, size_type n, const hasher& hf,
                          const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`a`
作为分配器以及默认的键相等性谓词，并将 `++[++f, l)`
范围内的元素插入其中。

[cols=",",]
|===
|要求： |`key++_++equal`
需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_initializer_list_constructor_with_allocator]]
===== 带分配器的初始化列表构造函数

[source,highlight]
----
concurrent_node_map(std::initializer_list<value_type> il, const allocator_type& a);
----

构造一个空容器，使用 `a`
作为分配器以及默认的哈希函数和键相等性谓词，并将 `il` 中的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 与 `key++_++equal`
需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_initializer_list_constructor_with_bucket_count_and_allocator]]
===== 带桶数和分配器的初始化列表构造函数

[source,highlight]
----
concurrent_node_map(std::initializer_list<value_type> il, size_type n, const allocator_type& a);
----

构造一个空容器，使用 `a`
作为分配器以及默认的哈希函数和键相等性谓词，并将 `il` 中的元素插入其中。

[cols=",",]
|===
|要求： |`hasher` 与 `key++_++equal`
需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_initializer_list_constructor_with_bucket_count_and_hasher_and_allocator]]
===== 带桶数、哈希函数和分配器的初始化列表构造函数

[source,highlight]
----
concurrent_node_map(std::initializer_list<value_type> il, size_type n, const hasher& hf,
                    const allocator_type& a);
----

构造一个至少包含 `n` 个桶的空容器，使用 `hf` 作为哈希函数、`a`
作为分配器以及默认的键相等性谓词，并将 `il` 中的元素插入其中。

[cols=",",]
|===
|要求： |`key++_++equal`
需满足 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]要求。
|===

'''''

[[concurrent_node_map_destructor]]
==== 析构函数

[source,highlight]
----
~concurrent_node_map();
----

[cols=",",]
|===
|注意： |析构函数会作用于每个元素，并释放所有内存
|===

'''''

[[concurrent_node_map_assignment]]
==== 赋值操作

[[concurrent_node_map_copy_assignment]]
===== 复制赋值

[source,highlight]
----
concurrent_node_map& operator=(concurrent_node_map const& other);
----

赋值操作符。该操作会销毁容器中原有的元素，并从 `other`
复制赋值哈希函数与键相等性谓词。若
`Alloc::propagate++_++on++_++container++_++copy++_++assignment` 存在，且
`Alloc::propagate++_++on++_++container++_++copy++_++assignment::value`
为 `true`，则从 `other` 复制赋值分配器，最后插入 `other`
中所有元素的副本。

[cols=",",]
|===
|要求： |`value++_++type`
需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求

|并发性： |阻塞于 `++*++this` 和 `other`。
|===

'''''

[[concurrent_node_map_move_assignment]]
===== 移动赋值

[source,highlight]
----
concurrent_node_map& operator=(concurrent_node_map&& other)
  noexcept((boost::allocator_traits<Allocator>::is_always_equal::value ||
            boost::allocator_traits<Allocator>::propagate_on_container_move_assignment::value) &&
            std::is_same<pointer, value_type*>::value);
----

移动赋值运算符。该操作会销毁先前存在的元素，交换 `other`
的哈希函数和谓词，若
`Alloc::propagate++_++on++_++container++_++move++_++assignment` 存在且其
`Alloc::propagate++_++on++_++container++_++move++_++assignment::value`
为 `true`，则从 `other` 移动赋值分配器。若此时分配器与
`other.get++_++allocator()`相等，则将 `other` 的内部桶数组直接转移至
`++*++this`；否则，插入 `other`
元素的移动构造副本。若统计功能link:#concurrent_node_map_boost_unordered_enable_stats[已启用]，则当最终分配器等于
`other.get++_++allocator()` 时转移 `other` 的内部统计信息，并始终调用
`other.reset++_++stats()`。

[cols=",",]
|===
|并发性： |阻塞于 `++*++this` 和 `other`。
|===

'''''

[[concurrent_node_map_initializer_list_assignment]]
===== 初始化列表赋值

[source,highlight]
----
concurrent_node_map& operator=(std::initializer_list<value_type> il);
----

从初始化列表中的值赋值。该操作销毁所有原有元素。

[cols=",",]
|===
|要求： |`value++_++type`
需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求

|并发性： |阻塞于 `++*++this`。
|===

'''''

[[concurrent_node_map_visitation]]
==== 访问操作

[[concurrent_node_map_cvisit]]
===== ++[++c++]++visit（++[++c++]++访问）

[source,highlight]
----
template<class F> size_t visit(const key_type& k, F f);
template<class F> size_t visit(const key_type& k, F f) const;
template<class F> size_t cvisit(const key_type& k, F f) const;
template<class K, class F> size_t visit(const K& k, F f);
template<class K, class F> size_t visit(const K& k, F f) const;
template<class K, class F> size_t cvisit(const K& k, F f) const;
----

如果存在键等价于`k`的元素`x`，则通过指向`x`的引用调用`f`。当且仅当
`++*++this` 为常量时，该引用也为常量引用。

[cols=",",]
|===
|返回： |被访问的元素数量（0 或 1）。

|注意： |仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent`
均为有效的成员类型别名时，`template++<++class K, class F++>++`
重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且
`Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。
|===

'''''

[[concurrent_node_map_bulk_visit]]
===== 批量访问

[source,highlight]
----
template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f);
template<class FwdIterator, class F>
  size_t visit(FwdIterator first, FwdIterator last, F f) const;
template<class FwdIterator, class F>
  size_t cvisit(FwdIterator first, FwdIterator last, F f) const;
----

对于范围++[++`first`,
`last`)中的每个元素`k`，如果容器中存在键等价于`k`的元素`x`，则通过指向`x`的引用来调用`f`。当且仅当
`++*++this` 为常量时，该引用也为 常量引用。

尽管在功能上等效于对每个键单独调用
link:#concurrent_node_map_cvisit[`++[++c++]++visit`]，但批量访问因内部流线型优化而通常具有更快的执行速度。建议
`std::distance(first,last)` 至少为
link:#concurrent_node_map_constants[`bulk++_++visit++_++size`]
以获得性能提升：超过此大小，性能预计不会进一步提升。

[cols=",",]
|===
|要求： |`FwdIterator` 需满足
 https://en.cppreference.com/w/cpp/named_req/ForwardIterator[LegacyForwardIterator]
要求（C{plus}{plus}11 至 C{plus}{plus}17）或符合
 https://en.cppreference.com/w/cpp/iterator/forward_iterator[std::forward++_++iterator]规范（C{plus}{plus}20
及更高版本）。对于`K` =
`std::iterator++_++traits++<++FwdIterator++>++::value++_++type`，需满足以下条件之一：`K`
与 `key++_++type` 类型相同，或 `Hash::is++_++transparent` 与
`Pred::is++_++transparent`
均为有效的成员类型别名。对于后一种情况，该库假定 `Hash` 可同时被 `K` 和
`Key` 调用，且 `Pred` 是透明的。该机制支持异构查找，从而避免了实例化
`Key` 类型对象所需的开销。

|返回： |返回被访问的元素数量。
|===

'''''

[[concurrent_node_map_cvisit_all]]
===== ++[++c++]++visit++_++all

[source,highlight]
----
template<class F> size_t visit_all(F f);
template<class F> size_t visit_all(F f) const;
template<class F> size_t cvisit_all(F f) const;
----

依次使用指向表中各元素的引用调用 `f`。当且仅当 `++*++this`
为常量时，该引用也为常量引用。

[cols=",",]
|===
|返回： |返回被访问的元素数量。
|===

'''''

[[concurrent_node_map_parallel_cvisit_all]]
===== 并行 ++[++c++]++visit++_++all

[source,highlight]
----
template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f);
template<class ExecutionPolicy, class F> void visit_all(ExecutionPolicy&& policy, F f) const;
template<class ExecutionPolicy, class F> void cvisit_all(ExecutionPolicy&& policy, F f) const;
----

根据指定的执行策略语义并行化执行，使用指向表中各元素的引用调用
`f`。当且仅当 `++*++this` 为常量时，该引用也为常量引用。

[width="100%",cols="50%,50%",]
|===
|抛出： |根据所用执行策略的异常处理机制，若在 `f` 内抛出异常，可能调用
`std::terminate`。

|注意： a|
仅在支持 C{plus}{plus}17 并行算法的编译器中可用。 +

仅当
`std::is++_++execution++_++policy++_++v++<++std::remove++_++cvref++_++t++<++ExecutionPolicy++>>++`
为 `true` 时，这些重载才参与重载决议。 +

不允许使用无序执行策略。

|===

'''''

[[concurrent_node_map_cvisit_while]]
===== ++[++c++]++visit++_++while

[source,highlight]
----
template<class F> bool visit_while(F f);
template<class F> bool visit_while(F f) const;
template<class F> bool cvisit_while(F f) const;
----

依次使用指向容器中各元素的引用来调用 `f`，直到 `f` 返回 `false`
或所有元素均被访问。当且仅当 `++*++this`
为常量时，指向元素的该引用也为常量引用。

[cols=",",]
|===
|返回： |当且仅当函数 `f` 曾返回 `false` 时，本函数才返回 `false`。
|===

'''''

[[concurrent_node_map_parallel_cvisit_while]]
===== 并行 ++[++c++]++visit++_++while

[source,highlight]
----
template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f);
template<class ExecutionPolicy, class F> bool visit_while(ExecutionPolicy&& policy, F f) const;
template<class ExecutionPolicy, class F> bool cvisit_while(ExecutionPolicy&& policy, F f) const;
----

依次使用指向容器中各元素的引用来调用 `f`，直到 `f` 返回 `false`
或所有元素均被访问。当且仅当 `++*++this`
为常量时，指向元素的该引用也为常量引用。根据指定的执行策略语义并行化执行操作。

[width="100%",cols="50%,50%",]
|===
|返回： |当且仅当函数 `f` 曾返回 `false` 时，本函数才返回 `false`。

|抛出： |根据所用执行策略的异常处理机制，若在 `f` 内抛出异常，可能调用
`std::terminate`。

|注意： a|
仅在支持 C{plus}{plus}17 并行算法的编译器中可用。 +

仅当
`std::is++_++execution++_++policy++_++v++<++std::remove++_++cvref++_++t++<++ExecutionPolicy++>>++`
为 `true` 时，这些重载才参与重载决议。 +

不允许使用无序执行策略。 +

并行化意味着执行不一定会因 `f` 返回 `false`
而立即结束，因此系统可能继续使用其他元素调用 `f`（即使其返回值同样为
`false`）。

|===

'''''

[[concurrent_node_map_size_and_capacity]]
==== 大小与容量

[[concurrent_node_map_empty]]
===== 空

[source,highlight]
----
[[nodiscard]] bool empty() const noexcept;
----

[cols=",",]
|===
|返回： |`size() == 0`
|===

'''''

[[concurrent_node_map_size]]
===== 大小

[source,highlight]
----
size_type size() const noexcept;
----

[cols=",",]
|===
|返回： |容器中的元素数量。
|===

[cols=",",]
|===
|注意：
|在存在并发插入操作的情况下，返回值可能无法准确反映执行完成后容器的真实大小。
|===

'''''

[[concurrent_node_map_max_size]]
===== max++_++size

[source,highlight]
----
size_type max_size() const noexcept;
----

[cols=",",]
|===
|返回： |返回该容器可能包含的最大元素数量`size()`。
|===

'''''

[[concurrent_node_map_modifiers]]
==== 修改器

[[concurrent_node_map_emplace]]
===== 原地构造

[source,highlight]
----
template<class... Args> bool emplace(Args&&... args);
----

当且仅当容器中不存在具有等效键的元素时，插入一个由参数 `args`
构造的对象。

[cols=",",]
|===
|要求： |`value++_++type` 必须能够从 `args` 构造。

|返回： |若插入操作发生，则返回 `true`。

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |若 `args…​` 的格式为
`k,v`，该实现会延迟构造完整对象，直到确认需要插入元素时为止，在此期间仅使用参数
`k` 进行检查。
|===

'''''

[[concurrent_node_map_copy_insert]]
===== 复制插入

[source,highlight]
----
bool insert(const value_type& obj);
bool insert(const init_type& obj);
----

当且仅当容器中不存在等价键的元素时，插入 `obj`。

[width="100%",cols="50%,50%",]
|===
|要求： |`value++_++type`
需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|返回： |若插入操作发生，则返回 `true`。 +

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |对于 `insert(x)`
形式的调用（其中`x`可同等地转换为`const value++_++type&`和`const init++_++type&`），该调用不会产生歧义，并选择`init++_++type`重载。
|===

'''''

[[concurrent_node_map_move_insert]]
===== 移动插入

[source,highlight]
----
bool insert(value_type&& obj);
bool insert(init_type&& obj);
----

当且仅当容器中不存在等价键的元素时，插入 `obj`。

[cols=",",]
|===
|要求： |`value++_++type`
需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]要求。

|返回： |若插入操作发生，则返回 `true`。

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |对于 `insert(x)`
形式的调用（其中`x`可同等地转换为`const value++_++type&` 和
`const init++_++type&`），不会产生歧义，并选择`init++_++type`重载。
|===

'''''

[[concurrent_node_map_insert_iterator_range]]
===== 迭代器范围插入

[source,highlight]
----
template<class InputIterator> size_type insert(InputIterator first, InputIterator last);
----

等效于

....
  while(first != last) this->emplace(*first++);
....

[cols=",",]
|===
|返回： |返回被插入的元素数量。
|===

'''''

[[concurrent_node_map_insert_initializer_list]]
===== 初始化列表插入

[source,highlight]
----
size_type insert(std::initializer_list<value_type> il);
----

等效于

....
  this->insert(il.begin(), il.end());
....

[cols=",",]
|===
|返回： |返回被插入的元素数量。
|===

'''''

[[concurrent_node_map_insert_node]]
===== 节点插入

[source,highlight]
----
insert_return_type insert(node_type&& nh);
----

若 `nh` 非空，则当且仅当容器中不存在键等价于 `nh.key()`
的元素时，插入关联元素。函数返回时 `nh` 为空。

[width="100%",cols="50%,50%",]
|===
|返回： a|
返回一个由 `inserted` 和 `node` 构造的 `insert++_++return++_++type`
对象： +

* 若 `nh` 为空，则 `inserted` 返回 `false` 且 `node` 为空。
* 否则若插入发生，则 `inserted` 返回 true 且 `node` 为空。
* 若插入失败，则 `inserted` 返回 false 且 `node` 具有 `nh` 的先前值。

|抛出： |若异常由调用 `hasher` 以外的操作抛出，则此函数不产生任何效果。

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |若 `nh` 非空且 `nh`
的分配器与容器的分配器不相等，则行为未定义。
|===

'''''

[[concurrent_node_map_emplace_or_cvisit]]
===== emplace++_++or++_[++c++]++visit

[source,highlight]
----
template<class... Args, class F> bool emplace_or_visit(Args&&... args, F&& f);
template<class... Args, class F> bool emplace_or_cvisit(Args&&... args, F&& f);
----

如果容器中不存在等价键的元素，则插入一个用参数`args`构造的对象。否则，使用执行等价元素的引用来调用`f`；如果使用`emplace++_++or++_++cvisit`时，该引用为常量引用）。

[cols=",",]
|===
|要求： |`value++_++type` 必须能够从 `args` 构造。

|返回： |若插入操作发生，则返回 `true`。

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |此接口仅为说明，因 C{plus}{plus} 不允许在可变参数包后声明参数
`f`。
|===

'''''

[[concurrent_node_map_copy_insert_or_cvisit]]
===== 复制 insert++_++or++_[++c++]++visit

[source,highlight]
----
template<class F> bool insert_or_visit(const value_type& obj, F f);
template<class F> bool insert_or_cvisit(const value_type& obj, F f);
template<class F> bool insert_or_visit(const init_type& obj, F f);
template<class F> bool insert_or_cvisit(const init_type& obj, F f);
----

当且仅当容器中不存在等价键的元素时，插入
`obj`；否则，以等价元素的引用为参数调用 `f`；当且仅当使用 `++*_++cvisit`
重载时该引用为常量引用。

[width="100%",cols="50%,50%",]
|===
|要求： |`value++_++type`
需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|返回： |若插入操作发生，则返回 `true`。 +

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |在
`insert++_++or++_[++c++]++visit(obj, f)`形式的调用中，仅当`std::remove++_++cv++<++std::remove++_++reference++<++decltype(obj)++>++::type++>++::type`
为
`value++_++type`时，接受`const value++_++type&`参数的重载才会参与重载决议。
|===

'''''

[[concurrent_node_map_move_insert_or_cvisit]]
===== 移动 insert++_++or++_[++c++]++visit

[source,highlight]
----
template<class F> bool insert_or_visit(value_type&& obj, F f);
template<class F> bool insert_or_cvisit(value_type&& obj, F f);
template<class F> bool insert_or_visit(init_type&& obj, F f);
template<class F> bool insert_or_cvisit(init_type&& obj, F f);
----

当且仅当容器中不存在等价键的元素时，插入
`obj`；否则，以等价元素的引用为参数调用 `f`；当且仅当使用 `++*_++cvisit`
重载时该引用为常量引用。

[width="100%",cols="50%,50%",]
|===
|要求： |`value++_++type`
需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]要求。

|返回： |若插入操作发生，则返回 `true`。 +

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意：
|在`insert++_++or++_[++c++]++visit(obj, f)`形式的调用中，仅当`std::remove++_++reference++<++decltype(obj)++>++::type`
为
`value++_++type`时，接受`value++_++type&&`参数的重载才会参与重载决议。
|===

'''''

[[concurrent_node_map_insert_iterator_range_or_visit]]
===== 迭代器范围插入或访问

[source,highlight]
----
template<class InputIterator,class F>
    size_type insert_or_visit(InputIterator first, InputIterator last, F f);
template<class InputIterator,class F>
    size_type insert_or_cvisit(InputIterator first, InputIterator last, F f);
----

等效于

....
  while(first != last) this->emplace_or_[c]visit(*first++, f);
....

[cols=",",]
|===
|返回： |返回被插入的元素数量。
|===

'''''

[[concurrent_node_map_insert_initializer_list_or_visit]]
===== 初始化列表插入或访问

[source,highlight]
----
template<class F> size_type insert_or_visit(std::initializer_list<value_type> il, F f);
template<class F> size_type insert_or_cvisit(std::initializer_list<value_type> il, F f);
----

等效于

....
  this->insert_or_[c]visit(il.begin(), il.end(), std::ref(f));
....

[cols=",",]
|===
|返回： |返回被插入的元素数量。
|===

'''''

[[concurrent_node_map_insert_node_or_visit]]
===== 节点插入或访问

[source,highlight]
----
template<class F> insert_return_type insert_or_visit(node_type&& nh, F f);
template<class F> insert_return_type insert_or_cvisit(node_type&& nh, F f);
----

若 `nh` 为空，则不执行任何操作。否则，当且仅当容器中不存在键等价于
`nh.key()` 的元素时，插入其关联的元素；否则，以等价元素的引用为参数调用
`f`；当且仅当使用 `insert++_++or++_++cvisit` 时该引用为常量引用。

[width="100%",cols="50%,50%",]
|===
|返回： a|
返回一个由 `inserted` 和 `node` 构造的 `insert++_++return++_++type`
对象： +

* 若 `nh` 为空，则 `inserted` 返回 `false` 且 `node` 为空。
* 否则若插入发生，则 `inserted` 返回 true 且 `node` 为空。
* 若插入失败，则 `inserted` 返回 false 且 `node` 具有 `nh` 的先前值。

|抛出： |若异常由调用 `hasher` 或调用 `f`
以外的操作抛出，则此函数不产生任何效果。

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |若 `nh` 非空且 `nh`
的分配器与容器的分配器不相等，则行为未定义。
|===

'''''

[[concurrent_node_map_emplace_and_cvisit]]
===== emplace++_++and++_[++c++]++visit

[source,highlight]
----
template<class... Args, class F1, class F2>
  bool emplace_and_visit(Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool emplace_and_cvisit(Args&&... args, F1&& f1, F2&& f2);
----

当容器中不存在等价键的元素时，插入一个用参数`args`构造的对象，然后使用指向新创建元素的非常量引用来调用`f1`。否则，使用指向等价元素的引用来调用`f2`；（当使用
`emplace++_++and++_++cvisit` 时，该引用为常量引用）.

[cols=",",]
|===
|要求： |`value++_++type` 必须能够从 `args` 构造。

|返回： |若插入操作发生，则返回 `true`。

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |此接口仅为说明，因为 C{plus}{plus} 不允许在可变参数包后声明参数
`f1` 和 `f2`。
|===

'''''

[[concurrent_node_map_copy_insert_and_cvisit]]
===== 复制 insert++_++and++_[++c++]++visit

[source,highlight]
----
template<class F1, class F2> bool insert_and_visit(const value_type& obj, F1 f1, F2 f2);
template<class F1, class F2> bool insert_and_cvisit(const value_type& obj, F1 f1, F2 f2);
template<class F1, class F2> bool insert_and_visit(const init_type& obj, F1 f1, F2 f2);
template<class F1, class F2> bool insert_and_cvisit(const init_type& obj, F1 f1, F2 f2);
----

当且仅当容器中不存在等价键的元素时，插入
`obj`，并以新创建元素的非常量引用为参数调用
`f1`；否则，以等价元素的引用为参数调用 `f2`；当且仅当使用
`emplace++_++and++_++cvisit` 时该引用为常量引用。

[width="100%",cols="50%,50%",]
|===
|要求： |`value++_++type`
需满足 https://en.cppreference.com/w/cpp/named_req/CopyInsertable[可复制插入]要求。

|返回： |若插入操作发生，则返回 `true`。 +

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |在`insert++_++and++_[++c++]++visit(obj, f1, f2)`
形式的调用中，仅当`std::remove++_++cv++<++std::remove++_++reference++<++decltype(obj)++>++::type++>++::type`为`value++_++type`
时，接受`const value++_++type&` 参数的重载才会参与重载决议。
|===

'''''

[[concurrent_node_map_move_insert_and_cvisit]]
===== 移动 insert++_++and++_[++c++]++visit

[source,highlight]
----
template<class F1, class F2> bool insert_and_visit(value_type&& obj, F1 f1, F2 f2);
template<class F1, class F2> bool insert_and_cvisit(value_type&& obj, F1 f1, F2 f2);
template<class F1, class F2> bool insert_and_visit(init_type&& obj, F1 f1, F2 f2);
template<class F1, class F2> bool insert_and_cvisit(init_type&& obj, F1 f1, F2 f2);
----

当且仅当容器中不存在等价键的元素时，插入
`obj`，并以新创建元素的非常量引用为参数调用
`f1`；否则，以等价元素的引用为参数调用 `f2`；当且仅当使用
`emplace++_++and++_++cvisit` 时该引用为常量引用。

[width="100%",cols="50%,50%",]
|===
|要求： |`value++_++type`
需满足 https://en.cppreference.com/w/cpp/named_req/MoveInsertable[可移动插入]要求。

|返回： |若插入操作发生，则返回 `true`。 +

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意：
|在`insert++_++and++_[++c++]++visit(obj, f1, f2)`形式的调用中，仅当`std::remove++_++reference++<++decltype(obj)++>++::type`
为
`value++_++type`时，接受`value++_++type&&`参数的重载才会参与重载决议。
|===

'''''

[[concurrent_node_map_insert_iterator_range_and_visit]]
===== 迭代器范围插入并访问

[source,highlight]
----
template<class InputIterator, class F1, class F2>
    size_type insert_or_visit(InputIterator first, InputIterator last, F1 f1, F2 f2);
template<class InputIterator, class F1, class F2>
    size_type insert_or_cvisit(InputIterator first, InputIterator last, F1 f2, F2 f2);
----

等效于

....
  while(first != last) this->emplace_and_[c]visit(*first++, f1, f2);
....

[cols=",",]
|===
|返回： |返回被插入的元素数量。
|===

'''''

[[concurrent_node_map_insert_initializer_list_and_visit]]
===== 初始化列表插入并访问

[source,highlight]
----
template<class F1, class F2>
  size_type insert_and_visit(std::initializer_list<value_type> il, F1 f1, F2 f2);
template<class F1, class F2>
  size_type insert_and_cvisit(std::initializer_list<value_type> il, F1 f1, F2 f2);
----

等效于

....
  this->insert_and_[c]visit(il.begin(), il.end(), std::ref(f1), std::ref(f2));
....

[cols=",",]
|===
|返回： |返回被插入的元素数量。
|===

'''''

[[concurrent_node_map_insert_node_and_visit]]
===== 节点插入并访问

[source,highlight]
----
template<class F1, class F2>
  insert_return_type insert_and_visit(node_type&& nh, F1 f1, F2 f2);
template<class F1, class F2>
  insert_return_type insert_and_cvisit(node_type&& nh, F1 f1, F2 f2);
----

若 `nh` 为空，则不执行任何操作。否则，当且仅当容器中不存在键等价于
`nh.key()` 的元素时，插入关联元素，并以新插入元素的非常量引用为参数调用
`f1`；否则，以等价元素的引用为参数调用 `f2`；当且仅当使用
`insert++_++or++_++cvisit` （此处应为
`insert++_++and++_++cvisit`，可能是英文出了点错误）时该引用为常量引用。

[width="100%",cols="50%,50%",]
|===
|返回： a|
返回一个由 `inserted` 和 `node` 构造的 `insert++_++return++_++type`
对象： +

* 若 `nh` 为空，则 `inserted` 返回 `false` 且 `node` 为空。
* 否则若插入发生，则 `inserted` 返回 true 且 `node` 为空。
* 若插入失败，则 `inserted` 返回 false 且 `node` 具有 `nh` 的先前值。

|抛出： |若异常由调用 `hasher`、`f1` 或 `f2`
以外的操作抛出，则此函数不产生任何效果。

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |若 `nh` 非空且 `nh`
的分配器与容器的分配器不相等，则行为未定义。
|===

'''''

[[concurrent_node_map_try_emplace]]
===== try++_++emplace

[source,highlight]
----
template<class... Args> bool try_emplace(const key_type& k, Args&&... args);
template<class... Args> bool try_emplace(key_type&& k, Args&&... args);
template<class K, class... Args> bool try_emplace(K&& k, Args&&... args);
----

如果容器中不存在键为`k`的元素，则插入一个由`k`和`args`构造的元素。

[width="100%",cols="50%,50%",]
|===
|返回： |若插入操作发生，则返回 `true`。 +

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： a|
此函数与
link:#concurrent_node_map_emplace[emplace]类似，区别在于：若存在等价键的元素，则不会构造任何
`value++_++type`；否则，将按以下形式执行构造： +

[source,highlight]
----
// 前两个重载
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// 第三个重载
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))
----

与
link:#concurrent_node_map_emplace[emplace]不同——该操作仅将所有参数直接转发给
`value++_++type` 的构造函数。

仅当`Hash::is++_++transparent`和`Pred::is++_++transparent`均为有效的成员类别名义时，`template++<++class K, class... Args++>++`重载会才参与重决议析。标准库假设`Hash`可同时被
`K`和`Key`类型调用，且`Pred`为透明的。该机制支持异构查找，从而避免实例化
`Key` 类型的开销。

|===

'''''

[[concurrent_node_map_try_emplace_or_cvisit]]
===== try++_++emplace++_++or++_[++c++]++visit

[source,highlight]
----
template<class... Args, class F>
  bool try_emplace_or_visit(const key_type& k, Args&&... args, F&& f);
template<class... Args, class F>
  bool try_emplace_or_cvisit(const key_type& k, Args&&... args, F&& f);
template<class... Args, class F>
  bool try_emplace_or_visit(key_type&& k, Args&&... args, F&& f);
template<class... Args, class F>
  bool try_emplace_or_cvisit(key_type&& k, Args&&... args, F&& f);
template<class K, class... Args, class F>
  bool try_emplace_or_visit(K&& k, Args&&... args, F&& f);
template<class K, class... Args, class F>
  bool try_emplace_or_cvisit(K&& k, Args&&... args, F&& f);
----

如果容器中不存在键为`k`的元素，则插入一个由`k`和`args`构造的元素。否则，使用指向等价元素的引用调用`f`；当使用
`++*_++cvisit` 重载时，该引用为常量引用。

[width="100%",cols="50%,50%",]
|===
|返回： |若插入操作发生，则返回 `true`。 +

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： a|
若存在等价键的元素，则不构造任何 `value++_++type`
对象；否则，将按以下形式执行构造： +

[source,highlight]
----
// 前四个重载
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// 后两个重载
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))
----

此接口仅为说明，因 C{plus}{plus} 不允许在可变参数包后声明参数 `f`。

仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent`
均为有效的成员类型别名时，`template++<++class K, class... Args, class F++>++`
重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且
`Pred` 是透明的。该机制支持异构查找，从而避免了实例化 `Key`
类型对象所需的开销。

|===

'''''

[[concurrent_node_map_try_emplace_and_cvisit]]
===== try++_++emplace++_++and++_[++c++]++visit

[source,highlight]
----
template<class... Args, class F1, class F2>
  bool try_emplace_and_visit(const key_type& k, Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool try_emplace_and_cvisit(const key_type& k, Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool try_emplace_and_visit(key_type&& k, Args&&... args, F1&& f1, F2&& f2);
template<class... Args, class F1, class F2>
  bool try_emplace_and_cvisit(key_type&& k, Args&&... args, F1&& f1, F2&& f2);
template<class K, class... Args, class F1, class F2>
  bool try_emplace_and_visit(K&& k, Args&&... args, F1&& f1, F2&& f2);
template<class K, class... Args, class F1, class F2>
  bool try_emplace_and_cvisit(K&& k, Args&&... args, F1&& f1, F2&& f2);
----

若容器中不存在键为 `k` 的元素，则插入由 `k` 和 `args`
构造的元素，并使用指向新创建元素的非常量引用调用
`f1`；否则，使用指向等效元素的引用调用 `f2`；当使用 `++*_++cvisit`
重载时，该引用为常量引用。

[width="100%",cols="50%,50%",]
|===
|返回： |若插入操作发生，则返回 `true`。 +

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： a|
若存在等价键的元素，则不构造任何 `value++_++type`
对象；否则，将按以下形式执行构造： +

[source,highlight]
----
// 前四个重载
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))

// 后两个重载
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<Args>(args)...))
----

此接口仅为说明，因 C{plus}{plus} 不允许在可变参数包后声明参数 `f1` 和
`f2`。

仅当 `Hash::is++_++transparent` 与 `Pred::is++_++transparent`
均为有效的成员类型别名时，`template++<++class K, class... Args, class F1, class F2++>++`
重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且
`Pred` 为透明的。该机制支持异构查找，从而避免了实例化 `Key`
类型对象所需的开销。

|===

'''''

[[concurrent_node_map_insert_or_assign]]
===== insert++_++or++_++assign

[source,highlight]
----
template<class M> bool insert_or_assign(const key_type& k, M&& obj);
template<class M> bool insert_or_assign(key_type&& k, M&& obj);
template<class K, class M> bool insert_or_assign(K&& k, M&& obj);
----

向容器中插入新元素，或通过赋值给已存在的元素值来更新该元素。

如果存在键为`k`的元素，则通过赋值`std::forward++<++M++>++(obj)`来更新该元素。

如果不存在这样的元素，则将其以如下方式添加到容器中：

[source,highlight]
----
// 前两个重载
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<Key>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))

// 第三个重载
value_type(std::piecewise_construct,
           std::forward_as_tuple(std::forward<K>(k)),
           std::forward_as_tuple(std::forward<M>(obj)))
----

[cols=",",]
|===
|返回： |若插入操作发生，则返回 `true`。

|并发性： |阻塞于 `++*++this` 的重哈希。

|注意： |仅当`Hash::is++_++transparent` 和 `Pred::is++_++transparent`
均为有效的成员类型别名时，`template++<++class K, class M++>++`
才会参与重载决议。标准库假设`Hash`可同时被`K` 与 `Key`
类型调用，且`Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key`
类型对象所需的开销。
|===

'''''

[[concurrent_node_map_erase]]
===== 擦除

[source,highlight]
----
size_type erase(const key_type& k);
template<class K> size_type erase(const K& k);
----

若存在键等价于 `k` 的元素，则擦除该元素。

[cols=",",]
|===
|返回： |返回被擦除的元素数量（0 或 1）。

|抛出： |仅当 `hasher` 或 `key++_++equal` 抛出异常时才会抛出异常。

|注意： |仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent`
均为有效的成员类型定义时，`template++<++class K++>++`
重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key`
类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key`
类型的开销。
|===

'''''

[[concurrent_node_map_erase_if_by_key]]
===== 通过键进行条件擦除

[source,highlight]
----
template<class F> size_type erase_if(const key_type& k, F f);
template<class K, class F> size_type erase_if(const K& k, F f);
----

若存在键等价于 `k` 的元素 `x` ，且 `f(x)` 为 `true`，则擦除该元素。

[width="100%",cols="50%,50%",]
|===
|返回： |返回被擦除的元素数量（0 或 1）。

|抛出： |仅当 `hasher`、`key++_++equal` 或 `f`
抛出异常时，本函数才会抛出异常。

|注意： a|
向 `f` 传递指向 `x` 的非常量引用。 +

仅当
`std::is++_++execution++_++policy++_++v++<++std::remove++_++cvref++_++t++<++ExecutionPolicy++>>++`
为 `false` 时，`template++<++class K, class F++>++`
重载才会参与重载决议。 +

仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent`
均为有效的成员类型别名时，`template++<++class K, class F++>++`
重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key` 调用，且
`Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key` 类型的开销。

|===

'''''

[[concurrent_node_map_erase_if]]
===== 条件擦除

[source,highlight]
----
template<class F> size_type erase_if(F f);
----

依次使用指向表中各元素的非常量引用调用 `f`，并删除其中使 `f` 返回 `true`
的元素。

[cols=",",]
|===
|返回： |被擦除的元素数量。
|抛出： |仅当 `f` 抛出异常时，才会抛出异常。
|===

'''''

[[concurrent_node_map_parallel_erase_if]]
===== 并行条件擦除

[source,highlight]
----
template<class ExecutionPolicy, class  F> void erase_if(ExecutionPolicy&& policy, F f);
----

根据指定的执行策略语义并行化执行一下操作：使用指向表中各元素的非常量引用调用
`f`，并删除其中使 `f` 返回 `true` 的元素。

[width="100%",cols="50%,50%",]
|===
|抛出： |根据所用执行策略的异常处理机制，若在 `f` 内抛出异常，可能调用
`std::terminate`。

|注意： a|
仅在支持 C{plus}{plus}17 并行算法的编译器中可用。 +

仅当
`std::is++_++execution++_++policy++_++v++<++std::remove++_++cvref++_++t++<++ExecutionPolicy++>>++`
为 `true` 时，此重载才会参与重载决议。 +

不允许使用无序执行策略。

|===

'''''

[[concurrent_node_map_swap]]
===== 交换

[source,highlight]
----
void swap(concurrent_node_map& other)
  noexcept(boost::allocator_traits<Allocator>::is_always_equal::value ||
           boost::allocator_traits<Allocator>::propagate_on_container_swap::value);
----

交换容器与参数的内容。

若 `Allocator::propagate++_++on++_++container++_++swap`已声明， 且其
`value` 为
`true`，则交换容器的分配器；否则，在分配器不相等的情况下进行交换将导致未定义行为。

[cols=",",]
|===
|抛出： |除非异常由 `key++_++equal` 或 `hasher`
在交换时抛出，否则本操作不会抛出任何异常。

|并发性： |阻塞于 `++*++this` 和 `other`。
|===

'''''

[[concurrent_node_map_extract]]
===== extract

[source,highlight]
----
node_type extract(const key_type& k);
template<class K> node_type extract(K&& k);
----

若存在键等价于 `k` 的元素，则提取该元素。

[cols=",",]
|===
|返回： |返回包含被提取元素的 `node++_++type`
对象，未提取任何元素，则返回空对象。

|抛出： |仅当 `hasher` 或 `key++_++equal` 抛出异常时才会抛出异常。

|注意： |仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent`
均为有效的成员类型定义时，`template++<++class K++>++`
重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key`
类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key`
类型的开销。
|===

'''''

[[concurrent_node_map_extract_if]]
===== 条件提取

[source,highlight]
----
template<class F> node_type extract_if(const key_type& k, F f);
template<class K, class F> node_type extract_if(K&& k, F f);
----

若存在键等价于 `k` 的元素 `x` ，且 `f(x)` 为 `true`，则提取该元素。

[cols=",",]
|===
|返回： |返回包含被提取元素的 `node++_++type`
对象，未提取任何元素，则返回空对象。

|抛出： |仅当 `hasher`、`key++_++equal` 或 `f`
抛出异常时，才会抛出异常。

|注意： |仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent`
均为有效的成员类型定义时，`template++<++class K++>++`
重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key`
类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key`
类型的开销。
|===

'''''

[[concurrent_node_map_clear]]
===== 清空

[source,highlight]
----
void clear() noexcept;
----

擦除容器中所有元素。

[cols=",",]
|===
|后置条件：
|`size() == 0`，`max++_++load() ++>++= max++_++load++_++factor() ++*++ bucket++_++count()`

|并发性： |阻塞于 `++*++this`。
|===

'''''

[[concurrent_node_map_merge]]
===== 合并

[source,highlight]
----
template<class H2, class P2>
  size_type merge(concurrent_node_map<Key, T, H2, P2, Allocator>& source);
template<class H2, class P2>
  size_type merge(concurrent_node_map<Key, T, H2, P2, Allocator>&& source);
----

对 `source` 中所有键不在 `++*++this`
中的元素执行移动插入操作，并将这些元素从 `source` 中擦除。

[cols=",",]
|===
|返回： |返回被插入的元素数量。
|并发性： |阻塞于 `++*++this` 和 `source`。
|===

'''''

[[concurrent_node_map_observers]]
==== 观察器

[[concurrent_node_map_get_allocator]]
===== get++_++allocator

[source,highlight]
----
allocator_type get_allocator() const noexcept;
----

[cols=",",]
|===
|返回： |容器的分配器。
|===

'''''

[[concurrent_node_map_hash_function]]
===== 哈希函数

[source,highlight]
----
hasher hash_function() const;
----

[cols=",",]
|===
|返回： |容器的哈希函数。
|===

'''''

[[concurrent_node_map_key_eq]]
===== key++_++eq

[source,highlight]
----
key_equal key_eq() const;
----

[cols=",",]
|===
|返回： |容器的键相等性谓词。
|===

'''''

[[concurrent_node_map_map_operations]]
==== 映射操作

[[concurrent_node_map_count]]
===== count

[source,highlight]
----
size_type        count(const key_type& k) const;
template<class K>
  size_type      count(const K& k) const;
----

[width="100%",cols="50%,50%",]
|===
|返回： |键等价于 `k` 的元素数量（0 或 1）。

|注意： a|
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent`
均为有效的成员类型定义时，`template++<++class K++>++`
重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key`
类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key`
类型的开销。 +

在存在并发插入操作的情况下，返回值可能无法准确反映函数执行完成后容器的真实状态。

|===

'''''

[[concurrent_node_map_contains]]
===== 包含

[source,highlight]
----
bool             contains(const key_type& k) const;
template<class K>
  bool           contains(const K& k) const;
----

[width="100%",cols="50%,50%",]
|===
|返回： |返回布尔值，表示容器中是否存在键等于 `k` 的元素。

|注意： a|
仅当 `Hash::is++_++transparent` 和 `Pred::is++_++transparent`
均为有效的成员类型定义时，`template++<++class K++>++`
重载才会参与重载决议。标准库假定 `Hash` 可同时被 `K` 和 `Key`
类型调用，且 `Pred` 为透明的。该机制支持异构查找，从而避免实例化 `Key`
类型的开销。 +

在存在并发插入操作的情况下，返回值可能无法准确反映函数执行完成后容器的真实状态。

|===

'''''

[[concurrent_node_map_bucket_interface]]
==== 桶接口

[[concurrent_node_map_bucket_count]]
===== bucket++_++count

[source,highlight]
----
size_type bucket_count() const noexcept;
----

[cols=",",]
|===
|返回： |桶数组的大小。
|===

'''''

[[concurrent_node_map_hash_policy]]
==== 哈希策略

[[concurrent_node_map_load_factor]]
===== 负载因子

[source,highlight]
----
float load_factor() const noexcept;
----

[cols=",",]
|===
|返回： |返回
`static++_++cast++<++float++>++(size())/static++_++cast++<++float++>++(bucket++_++count())`，若
`bucket++_++count() == 0`， 则返回 `0`。
|===

'''''

[[concurrent_node_map_max_load_factor]]
===== max++_++load++_++factor（最大负载因子）

[source,highlight]
----
float max_load_factor() const noexcept;
----

[cols=",",]
|===
|返回： |返回容器的最大负载因子。
|===

'''''

[[concurrent_node_map_set_max_load_factor]]
===== 设置最大负载因子

[source,highlight]
----
void max_load_factor(float z);
----

[cols=",",]
|===
|效果： |不执行任何操作，因为用户不允许修改此参数。保留此接口是为了与
`boost::unordered++_++map` 保持兼容。
|===

'''''

[[concurrent_node_map_max_load]]
===== max++_++load（最大负载）

[source,highlight]
----
size_type max_load() const noexcept;
----

[width="100%",cols="50%,50%",]
|===
|返回：
|返回容器在无需重哈希的情况下所能容纳的最大元素数量（假设后续无元素被删除）。

|注意： a|
在构造、重哈希或清空操作后，容器的最大负载至少为
`max++_++load++_++factor() ++*++ bucket++_++count()`。在高负载条件下执行擦除操作时，此数值可能会降低。 +

在存在并发插入操作的情况下，返回值可能无法准确反映函数执行完成后容器的真实状态。

|===

'''''

[[concurrent_node_map_rehash]]
===== 重哈希

[source,highlight]
----
void rehash(size_type n);
----

如有必要，将改变桶数组的大小，使其至少包含 `n`
个桶，并确保负载因子小于或等于最大负载因子。此操作将根据情况增加或减少容器的
`bucket++_++count()`。

当 `size() == 0` 时，`rehash(0)` 将释放底层桶数组。

[width="100%",cols="50%,50%",]
|===
|抛出：
|若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。

|并发性： a|
阻塞于 `++*++this`。

'''''

|===

[[concurrent_node_map_reserve]]
===== 保留

[source,highlight]
----
void reserve(size_type n);
----

等价于 `a.rehash(ceil(n / a.max++_++load++_++factor()))`。

与 `rehash` 类似，此函数可用于增加或减少容器中的桶数量。

[cols=",",]
|===
|抛出：
|若抛出异常（除非异常由容器的哈希函数或比较函数抛出），则该函数不产生任何效果。

|并发性： |阻塞于 `++*++this`。
|===

'''''

[[concurrent_node_map_statistics]]
==== 统计信息

[[concurrent_node_map_get_stats]]
===== get++_++stats

[source,highlight]
----
stats get_stats() const;
----

[cols=",",]
|===
|返回： |返回容器截至目前所执行的插入与查找操作的统计信息。

|注意：
|仅在link:reference/stats_zh_Hans.adoc#stats[统计计算]功能link:#concurrent_node_map_boost_unordered_enable_stats[启用]时可用。
|===

'''''

[[concurrent_node_map_reset_stats]]
===== reset++_++stats

[source,highlight]
----
void reset_stats() noexcept;
----

[cols=",",]
|===
|效果： |将容器所保存的内部统计信息重置为零。

|注意：
|仅在link:reference/stats_zh_Hans.adoc#stats[统计计算]功能link:#concurrent_node_map_boost_unordered_enable_stats[启用]时可用。
|===

'''''

[[concurrent_node_map_deduction_guides]]
==== 推导指引

如果以下任何一条件为真，则推导指引将不参与重载决议：

* 该推导指引包含 `InputIterator`
模板参数，且为此参数推导出的类型不符合输入迭代器的要求。
* 该推导指引包含 `Allocator`
模板参数，且为该参数推导出的类型不符合分配器要求。
* 该推导指引包含 `Hash`
模板参数，且为该参数推导出的类型为整型或符合分配器要求。
* 该推导指引包含 `Pred` 模板参数，且为该参数推导出的类型符合分配器要求。

推导指引中的 `size++_++type` 参数类型，指向由该推导指引所推导容器类型的
`size++_++type` 成员类型。其默认值与所选构造函数的默认值一致。

[[concurrent_node_map_iter_value_type]]
===== _iter-value-type_

....
template<class InputIterator>
  using iter-value-type =
    typename std::iterator_traits<InputIterator>::value_type; // 仅用于说明
....

[[concurrent_node_map_iter_key_type]]
===== _iter-key-type_

....
template<class InputIterator>
  using iter-key-type = std::remove_const_t<
    std::tuple_element_t<0, iter-value-type<InputIterator>>>; // 仅用于说明
....

[[concurrent_node_map_iter_mapped_type]]
===== _iter-mapped-type_

....
template<class InputIterator>
  using iter-mapped-type =
    std::tuple_element_t<1, iter-value-type<InputIterator>>;  // 仅用于说明
....

[[concurrent_node_map_iter_to_alloc_type]]
===== _iter-to-alloc-type_

....
template<class InputIterator>
  using iter-to-alloc-type = std::pair<
    std::add_const_t<std::tuple_element_t<0, iter-value-type<InputIterator>>>,
    std::tuple_element_t<1, iter-value-type<InputIterator>>>; // 仅用于说明
....

[[concurrent_node_map_equality_comparisons]]
==== 相等性比较

[[concurrent_node_map_operator]]
===== operator==

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator==(const concurrent_node_map<Key, T, Hash, Pred, Alloc>& x,
                  const concurrent_node_map<Key, T, Hash, Pred, Alloc>& y);
----

若 `x.size() == y.size()` ，且对于 `x` 中的每个元素，`y`
中均存在一个具有相同键和相等值的元素（使用 `operator==`
比较值类型），则返回 `true`。

[cols=",",]
|===
|并发性： |阻塞于 `x` 和 `y`。
|注意： |若两个容器的相等性谓词不等价，则行为未定义。
|===

'''''

[[concurrent_node_map_operator_2]]
===== operator!=

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  bool operator!=(const concurrent_node_map<Key, T, Hash, Pred, Alloc>& x,
                  const concurrent_node_map<Key, T, Hash, Pred, Alloc>& y);
----

若 `x.size() == y.size()`，并且对于 `x` 中的每个元素，`y`
中均存在一个具有相同键和相等值的元素（使用`operator==`比较值类型），则返回
`false`。

[cols=",",]
|===
|并发性： |阻塞于 `x` 和 `y`。
|注意： |若两个容器的相等性谓词不等价，则行为未定义。
|===

'''''

[[concurrent_node_map_swap_2]]
==== 交换

[source,highlight]
----
template<class Key, class T, class Hash, class Pred, class Alloc>
  void swap(concurrent_node_map<Key, T, Hash, Pred, Alloc>& x,
            concurrent_node_map<Key, T, Hash, Pred, Alloc>& y)
    noexcept(noexcept(x.swap(y)));
----

等效于

....
x.swap(y);
....

'''''

[[concurrent_node_map_erase_if_2]]
==== 条件擦除

[source,highlight]
----
template<class K, class T, class H, class P, class A, class Predicate>
  typename concurrent_node_map<K, T, H, P, A>::size_type
    erase_if(concurrent_node_map<K, T, H, P, A>& c, Predicate pred);
----

等效于

....
c.erase_if(pred);
....

[[concurrent_node_map_serialization]]
==== 序列化

`concurrent++_++node++_++map` 可通过本库提供的 API，借助
link:../../../../../serialization/index.html[Boost.Serialization]
实现归档/检索功能。同时支持常规格式与 XML 格式的归档文件。

[[concurrent_node_map_saving_an_concurrent_node_map_to_an_archive]]
===== 将 concurrent++_++node++_++map 保存至归档

将 `concurrent++_++node++_++map` 容器`x` 中的所有元素保存至归档（XML
格式归档）`ar`中。

[cols=",",]
|===
|要求： |`std::remove++_++const++<++key++_++type++>++::type` 和
`std::remove++_++const++<++mapped++_++type++>++::type`
必须满足可序列化要求（XML 可序列化），且需要支持 Boost.Serialization 的
`save++_++construct++_++data`/`load++_++construct++_++data`
协议（该协议自动支持
 https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[可默认构造]
要求）。

|并发性： |阻塞于 `x`。
|===

'''''

[[concurrent_node_map_loading_an_concurrent_node_map_from_an_archive]]
===== 从归档加载 concurrent++_++node++_++map

删除 `concurrent++_++node++_++map`容器 `x`
中的所有现有元素，并从归档（XML 归档）`ar` 插入原始
`concurrent++_++node++_++map` 容器 `other` 的元素副本，这些副本保存在
`ar` 读取的存储中。

[cols=",",]
|===
|要求： |`x.key++_++equal()` 需要在功能上等价于
`other.key++_++equal()`。

|并发性： |阻塞于 `x`。
|===

[[footer]]
[[footer-text]]
最后更新于 2025年10月31日 21:33:55 UTC
