[[header]]

[[content]]
[[header_unordered_flat_map]]
=== `++<++boost/unordered/unordered++_++flat++_++map.hpp++>++` 概要

定义
link:reference/unordered_flat_map_zh_Hans.adoc#unordered_flat_map[`boost::unordered++_++flat++_++map`]
以及相关函数和别名模板。

....
namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class unordered_flat_map;

  // 相等比较
  template<class Key, class T, class Hash, class Pred, class Alloc>
    bool operator==(const unordered_flat_map<Key, T, Hash, Pred, Alloc>& x,
                    const unordered_flat_map<Key, T, Hash, Pred, Alloc>& y);

  template<class Key, class T, class Hash, class Pred, class Alloc>
    bool operator!=(const unordered_flat_map<Key, T, Hash, Pred, Alloc>& x,
                    const unordered_flat_map<Key, T, Hash, Pred, Alloc>& y);

  // 交换
  template<class Key, class T, class Hash, class Pred, class Alloc>
    void swap(unordered_flat_map<Key, T, Hash, Pred, Alloc>& x,
              unordered_flat_map<Key, T, Hash, Pred, Alloc>& y)
      noexcept(noexcept(x.swap(y)));

  // 擦除
  template<class K, class T, class H, class P, class A, class Predicate>
    typename unordered_flat_map<K, T, H, P, A>::size_type
      erase_if(unordered_flat_map<K, T, H, P, A>& c, Predicate pred);

  // Pmr 别名（C++17 及以上）
  namespace pmr {
    template<class Key,
             class T,
             class Hash = boost::hash<Key>,
             class Pred = std::equal_to<Key>>
    using unordered_flat_map =
      boost::unordered::unordered_flat_map<Key, T, Hash, Pred,
        std::pmr::polymorphic_allocator<std::pair<const Key, T>>>;
  } // 命名空间 pmr

} // 命名空间 unordered

using unordered::unordered_flat_map;

} // 命名空间 boost
....

[[footer]]
[[footer-text]]
最后更新于2025年 10月 31日 21:36:53 UTC
