[[header]]

[[content]]
[[header_concurrent_node_map]]
=== `++<++boost/unordered/concurrent++_++node++_++map.hpp++>++` 概要

定义
link:reference/concurrent_node_map_zh_Hans.adoc#concurrent_node_map[`boost::concurrent++_++node++_++map`]
以及相关函数和别名模板。

....
namespace boost {
namespace unordered {

  template<class Key,
           class T,
           class Hash = boost::hash<Key>,
           class Pred = std::equal_to<Key>,
           class Allocator = std::allocator<std::pair<const Key, T>>>
  class concurrent_node_map;

  // 相等比较
  template<class Key, class T, class Hash, class Pred, class Alloc>
    bool operator==(const concurrent_node_map<Key, T, Hash, Pred, Alloc>& x,
                    const concurrent_node_map<Key, T, Hash, Pred, Alloc>& y);

  template<class Key, class T, class Hash, class Pred, class Alloc>
    bool operator!=(const concurrent_node_map<Key, T, Hash, Pred, Alloc>& x,
                    const concurrent_node_map<Key, T, Hash, Pred, Alloc>& y);

  // 交换
  template<class Key, class T, class Hash, class Pred, class Alloc>
    void swap(concurrent_node_map<Key, T, Hash, Pred, Alloc>& x,
              concurrent_node_map<Key, T, Hash, Pred, Alloc>& y)
      noexcept(noexcept(x.swap(y)));

  // 擦除
  template<class K, class T, class H, class P, class A, class Predicate>
    typename concurrent_node_map<K, T, H, P, A>::size_type
      erase_if(concurrent_node_map<K, T, H, P, A>& c, Predicate pred);

  // Pmr别名（C++17及以上）
  namespace pmr {
    template<class Key,
             class T,
             class Hash = boost::hash<Key>,
             class Pred = std::equal_to<Key>>
    using concurrent_node_map =
      boost::unordered::concurrent_node_map<Key, T, Hash, Pred,
        std::pmr::polymorphic_allocator<std::pair<const Key, T>>>;
  } // 命名空间 pmr

} // 命名空间 unordered

using unordered::concurrent_node_map;

} // 命名空间 boost
....

[[footer]]
[[footer-text]]
最后更新于2025年 10月 31日 21:35:50 UTC
